language: node_js
node_js:
  - "5"
  - "6"
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - npm install -g gulp
script: gulp prep